blueprint:
  name: Device Event Logger
  author: yarafie
  domain: automation
  description: >
    Logs all events (Z2M, ZHA, deCONZ) into an input_text helper using YAML list format.
    Automatically filters Zigbee2MQTT events so only the selected device is logged.
    Automatically appends entries and trims the list to a maximum size.

    ⚠️ NOTE: You MUST manually create an input_text helper first.


  homeassistant:
    min_version: 2024.10.0
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/device_event_logger.yaml
#
# Define UI and default values
  input:
    # Device Selector
    device_watched:
      name: Device to Watch
      description: The device whose events will be logged.
      selector:
        device: {}
    # Log Text Helper
    log_helper:
      name: Text Helper Target
      description: input_text helper storing YAML list of events.
      selector:
        entity:
          domain: input_text
    # Max History of Log
    max_history:
      name: Max History Entries
      description: Max number of YAML log entries to keep.
      default: 50
      selector:
        number:
          min: 1
          max: 1000
          mode: slider
mode: queued
max_exceeded: silent
max: 100
# ─────────────────────────────────────────────
# TRIGGERS — Z2M, ZHA, deCONZ
# ─────────────────────────────────────────────
triggers:
  # Zigbee2MQTT (trigger everything; filter later)
  - trigger: mqtt
    id: zigbee2mqtt-event
    topic: zigbee2mqtt/+/action
  # ZHA
  - trigger: event
    id: zha-event
    event_type: zha_event
    event_data:
      device_id: !input device_watched
  # deCONZ
  - trigger: event
    id: deconz-event
    event_type: deconz_event
    event_data:
      device_id: !input device_watched
# ─────────────────────────────────────────────
# ACTIONS — Auto Z2M Filter, Append, History Limit
# ─────────────────────────────────────────────
actions:
  # 1. Auto-detect Zigbee2MQTT friendly name from device entities
  - variables:
      # First capture the device_id from the blueprint input
      device_id: !input device_watched
      # All entities under selected device
      dev_entities: "{{ device_entities(device_id) }}"
      # First entity name (e.g., sensor.ikea_styrbar_action)
      first_entity: "{{ dev_entities[0] if dev_entities|length > 0 else '' }}"
      # Extract object_id (ikea_styrbar_action)
      object_id: "{{ first_entity.split('.')[1] if first_entity != '' else '' }}"

      # Remove any trailing _action or _button or _click etc.
      z2m_name: >
        {% set name = object_id %}
        {% if name.endswith('_action') %}
          {{ name[:-7] }}
        {% elif name.endswith('_click') %}
          {{ name[:-6] }}
        {% elif name.endswith('_button') %}
          {{ name[:-7] }}
        {% else %}
          {{ name }}
        {% endif %}

  # 2. Filter Zigbee2MQTT so only this device is logged
  - choose:
      - conditions: >
          {{ trigger.id == 'zigbee2mqtt-event' and
             trigger.topic == 'zigbee2mqtt/' ~ z2m_name ~ '/action' }}
        sequence: []

      - conditions: "{{ trigger.id != 'zigbee2mqtt-event' }}"
        sequence: []

    default:
      # If Z2M event does NOT match selected device → stop
      - stop: "MQTT event does not match selected Z2M device."

  # 3. Build new YAML entry
  - variables:
      ts: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      dev_name: "{{ device_attr((!input device_watched), 'name') }}"
      payload: "{{ trigger | tojson }}"

      new_entry_yaml: >
        - time: {{ ts }}
          device: {{ dev_name }}
          event: {{ payload }}

  # 4. Load existing YAML from helper
  - variables:
      existing_yaml: >
        {%- if states[ (!input log_helper) ] | trim != '' -%}
          {{ states[ (!input log_helper) ] | from_yaml }}
        {%- else -%}
          []
        {%- endif -%}

  # 5. Append new entry
  - variables:
      combined_yaml: "{{ existing_yaml + (new_entry_yaml | from_yaml) }}"

  # 6. Trim to max history
  - variables:
      trimmed_yaml: >
        {{ combined_yaml | slice(-1 * (!input max_history)) }}

  # 7. Convert list back to YAML text
  - variables:
      final_output: "{{ trimmed_yaml | to_yaml }}"

  # 8. Write YAML back to helper
  - action: input_text.set_value
    target:
      entity_id: !input log_helper
    data:
      value: "{{ final_output }}"
