blueprint:
  name: Device Event Logger
  author: yarafie
  domain: automation
  description: >
    Logs all events (Zigbee2MQTT, ZHA, deCONZ) for a selected device
    into an input_text helper as a YAML list.

    Features:
      • Auto-detect Zigbee2MQTT device name from its entities
      • Append mode (never overwrites)
      • Maximum history size (oldest entries removed automatically)
      • Fully safe with queued mode (avoids race conditions)

    ⚠️ NOTE: You MUST manually create an input_text helper first.


  homeassistant:
    min_version: 2024.10.0
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/device_event_logger.yaml
#
# Define UI and default values
  input:
    # Device Selector
    device_watched:
      name: Device to Watch
      description: The device whose events will be logged.
      selector:
        device: {}
    # Log Text Helper
    log_helper:
      name: Text Helper Target
      description: Input_text entity storing the YAML log list.
      selector:
        entity:
          domain: input_text
    # Max History of Log
    max_history:
      name: Max History Entries
      description: Maximum number of YAML entries to keep.
      default: 50
      selector:
        number:
          min: 1
          max: 1000
          mode: slider
mode: queued
max: 100
max_exceeded: silent
# ─────────────────────────────────────────────
# TRIGGERS — Z2M, ZHA, deCONZ
# ─────────────────────────────────────────────
triggers:
  # Zigbee2MQTT (trigger everything; filter later)
  - trigger: mqtt
    id: zigbee2mqtt-event
    topic: zigbee2mqtt/+/action
  # ZHA
  - trigger: event
    id: zha-event
    event_type: zha_event
    event_data:
      device_id: !input device_watched
  # deCONZ
  - trigger: event
    id: deconz-event
    event_type: deconz_event
    event_data:
      device_id: !input device_watched
# ─────────────────────────────────────────────
# ACTIONS — Auto Z2M filter, Append, History, YAML output
# ─────────────────────────────────────────────
actions:
  # Define all blueprint inputs
  - variables:
  # 1. Auto-detect Zigbee2MQTT Friendly Name
      # Store blueprint inputs first
      device_id_var: !input device_watched
      log_helper_var: !input log_helper
      max_history_var: !input max_history
      # Get all entities under the selected device
      dev_entities: "{{ device_entities(device_id_var) }}"
      # First entity name (e.g., sensor.ikea_styrbar_lr_action)
      first_entity: "{{ dev_entities[0] if dev_entities|length > 0 else '' }}"
      # Extract object_id from entity (ikea_styrbar_lr_action)
      object_id: "{{ first_entity.split('.')[1] if first_entity else '' }}"

      # Clean up Zigbee2MQTT friendly name
      z2m_name: >
        {% set name = object_id %}
        {% if name.endswith('_action') %}
          {{ name[:-7] }}
        {% elif name.endswith('_click') %}
          {{ name[:-6] }}
        {% elif name.endswith('_button') %}
          {{ name[:-7] }}
        {% else %}
          {{ name }}
        {% endif %}

      # Readable device name
      dev_name: "{{ device_attr(device_id_var, 'name') }}"

      # Timestamp
      ts: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"


  # 2. Zigbee2MQTT filter (stop if MQTT topic doesn't match this device)
  - choose:
      - conditions: >
          {{ trigger.id == 'zigbee2mqtt-event'
             and trigger.topic != ('zigbee2mqtt/' ~ z2m_name ~ '/action') }}
        sequence:
          - stop: "Ignoring Z2M event from other device."
    default: []


  # 3. Build new YAML entry
  - variables:
      payload: "{{ trigger | tojson }}"
      new_entry_yaml: >
        - time: {{ ts }}
          device: {{ dev_name }}
          event: {{ payload }}


  # 4. Load existing YAML history from input_text
  - variables:
      existing_yaml: >
        {% if states[log_helper_var] | trim != '' %}
          {{ states[log_helper_var] | from_yaml }}
        {% else %}
          []
        {% endif %}

  # 5. Append new entry
  - variables:
      combined_yaml: "{{ existing_yaml + (new_entry_yaml | from_yaml) }}"

  # 6. Enforce max history limit
  - variables:
      trimmed_yaml: >
        {{ combined_yaml | slice(-1 * max_history_var) }}

  # 7. Convert list back into YAML formatted text
  - variables:
      final_output: "{{ trimmed_yaml | to_yaml }}"

  # 8. Write YAML into the input_text helper
  - action: input_text.set_value
    target:
      entity_id: "{{ log_helper_var }}"
    data:
      value: "{{ final_output }}"
