blueprint:
  name: Device Event Logger
  author: yarafie
  domain: automation
  description: >
    Logs all events (Zigbee2MQTT, ZHA, deCONZ) for a selected device
    into an input_text helper as a YAML list.

    Features:
      • Auto-detect Zigbee2MQTT device name from its entities
      • Append mode (never overwrites)
      • Maximum history size (oldest entries removed automatically)
      • Fully safe with queued mode (avoids race conditions)

    ⚠️ NOTE: You MUST manually create an input_text helper first.

  homeassistant:
    min_version: 2024.10.0
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/device_event_logger.yaml
#
# Define UI and default values
  input:
    # Device Selector
    device_logged:
      name: Device to Watch
      description: The device whose events will be logged.
      selector:
        device: {}
    # Log Text Helper
    log_helper:
      name: Text Helper Target
      description: Input_text entity storing the YAML log list.
      selector:
        entity:
          domain: input_text
    # Max History of Log
    max_history:
      name: Max History Entries
      description: Maximum number of YAML entries to keep.
      default: 50
      selector:
        number:
          min: 1
          max: 1000
          mode: slider
mode: queued
max: 100
max_exceeded: silent
# ─────────────────────────────────────────────
# TRIGGERS — Z2M, ZHA, deCONZ
# ─────────────────────────────────────────────
triggers:
  # Zigbee2MQTT (trigger everything; filter later)
  - trigger: mqtt
    id: z2m
    topic: zigbee2mqtt/+/action
  # ZHA
  - trigger: event
    id: zha
    event_type: zha_event
    event_data:
      device_id: !input device_logged
  # deCONZ
  - trigger: event
    id: deconz-event
    event_type: deconz
    event_data:
      device_id: !input device_logged
# ─────────────────────────────────────────────
# ACTIONS — Auto Z2M filter, Append, History, YAML output
# ─────────────────────────────────────────────
actions:
  # 1) Resolve inputs and derive identifiers
  - variables:
      device_id_var: !input device_logged
      log_helper_var: !input log_helper
      max_history_var: !input max_history

#      # Device identifiers, e.g. {('mqtt', 'zigbee2mqtt_0x94b216fffeefcc59')}
#      identifiers: "{{ device_attr(device_id_var, 'identifiers') }}"
#
#      # Extract MQTT/Z2M device name from identifiers
#      z2m_name: >
#        {% set result = '' %}
#        {% for item in identifiers %}
#          {% if item[0] == 'mqtt' %}
#            {% set result = item[1] %}
#          {% endif %}
#        {% endfor %}
#        {{ result }}

      # Human readable device name this is usually the devices friendly name
      dev_name: "{{ device_attr(device_id_var, 'name') }}"

      # Timestamp
      ts: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # 2) Filter Z2M: only keep events for this specific device
  - choose:
      - conditions: >
          {{ trigger.id == 'z2m'
             and dev_name != ''
             and trigger.topic != ('zigbee2mqtt/' ~ dev_name ~ '/action') }}
        sequence:
          - stop: "Skipping Zigbee2MQTT event from another device."
    default: []

  # Extract minimal action payload depending on integration
  - variables:
      action_value: >
        {% if trigger.id == 'z2m' %}
          {{ trigger.payload }}
        {% elif trigger.id == 'zha' %}
          {{ trigger.event.command }}
        {% elif trigger.id == 'deconz' %}
          {{ trigger.event.event }}
        {% else %}
          "?"
        {% endif %}


  # 3) Build new log entry as JSON string
  - variables:
      new_entry: >
        {{
          {
            "time": ts,
            "source": trigger.id,
            "device": dev_name,
            "action": action_value
          } | tojson
        }}

  # 4) Load existing JSON list safely
  - variables:
      raw_text: "{{ states(log_helper_var) | default('') | trim }}"
      # Normalize raw_text into JSON list
      existing_list: >
        {% if raw_text == '' or raw_text == 'unknown' %}
          []
        {% elif raw_text is string and raw_text | is_json %}
          {{ raw_text | from_json }}
        {% else %}
          []
        {% endif %}

  # 5) Append and trim
  - variables:
      updated_list: >
        {{ existing_list + [ new_entry | from_json ] }}

      trimmed_list: >
        {{ updated_list[-max_history_var:] }}

      final_json: "{{ trimmed_list | tojson }}"


  # 6) Save JSON array back to input_text
  - action: input_text.set_value
    target:
      entity_id: "{{ log_helper_var }}"
    data:
      value: "{{ final_json }}"
