blueprint:
  name: Device Event Logger
  author: yarafie
  domain: automation
  description: >
    Logs all events (Zigbee2MQTT, ZHA, deCONZ) for a selected device
    into an input_text helper as a YAML list.

    Features:
      • Auto-detect Zigbee2MQTT device name from its entities
      • Append mode (never overwrites)
      • Maximum history size (oldest entries removed automatically)
      • Fully safe with queued mode (avoids race conditions)

    ⚠️ NOTE: You MUST manually create an input_text helper first.


  homeassistant:
    min_version: 2024.10.0
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/device_event_logger.yaml
#
# Define UI and default values
  input:
    # Device Selector
    device_watched:
      name: Device to Watch
      description: The device whose events will be logged.
      selector:
        device: {}
    # Log Text Helper
    log_helper:
      name: Text Helper Target
      description: Input_text entity storing the YAML log list.
      selector:
        entity:
          domain: input_text
    # Max History of Log
    max_history:
      name: Max History Entries
      description: Maximum number of YAML entries to keep.
      default: 50
      selector:
        number:
          min: 1
          max: 1000
          mode: slider
mode: queued
max: 100
max_exceeded: silent
# ─────────────────────────────────────────────
# TRIGGERS — Z2M, ZHA, deCONZ
# ─────────────────────────────────────────────
triggers:
  # Zigbee2MQTT (trigger everything; filter later)
  - trigger: mqtt
    id: zigbee2mqtt-event
    topic: zigbee2mqtt/+/action
  # ZHA
  - trigger: event
    id: zha-event
    event_type: zha_event
    event_data:
      device_id: !input device_watched
  # deCONZ
  - trigger: event
    id: deconz-event
    event_type: deconz_event
    event_data:
      device_id: !input device_watched
# ─────────────────────────────────────────────
# ACTIONS — Auto Z2M filter, Append, History, YAML output
# ─────────────────────────────────────────────
actions:
  # Define all blueprint inputs
  - variables:
  # 1. Auto-detect Zigbee2MQTT Friendly Name
      # Store blueprint inputs first
      device_id_var: !input device_watched
      log_helper_var: !input log_helper
      max_history_var: !input max_history

      # Read device identifiers (Z2M ID stored here)
      identifiers: "{{ device_attr(device_id_var, 'identifiers') }}"
      # Extract Zigbee2MQTT device name from identifiers
      z2m_name: >
        {% set result = '' %}
        {% for item in identifiers %}
          {% if item is iterable and item|length == 2 and item[0] == 'zigbee2mqtt' %}
            {% set result = item[1] %}
          {% endif %}
        {% endfor %}
        {{ result }}
      # Readable device name
      dev_name: "{{ device_attr(device_id_var, 'name') }}"

      # Timestamp
      ts: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  # 2. Zigbee2MQTT filter (stop if MQTT topic doesn't match this device)
  - choose:
      - conditions: >
          {{ trigger.id == 'zigbee2mqtt-event'
             and trigger.topic != ('zigbee2mqtt/' ~ z2m_name ~ '/action') }}
        sequence:
          - stop: "Ignoring Z2M event from other device."
    default: []

  # 3. Build new JSON entry
  - variables:
      payload: "{{ trigger | tojson }}"
      new_entry: >
        {{
          {
            "time": ts,
            "device": dev_name,
            "source": trigger.id,
            "event": trigger
          }
          | tojson
        }}

  # 4. Load existing text and convert YAML → list of JSON objects
  - variables:
      raw_text: "{{ states[log_helper_var] | default('') }}"

      json_list: >
        {# If empty, return empty list #}
        {% if not raw_text or raw_text|trim == '' %}
          []
        {% else %}
          [
          {%- for block in raw_text.split('- time: ')[1:] -%}
            {%- set lines = ('time: ' ~ block).split('\n') -%}
            {
              "time": "{{ lines[0].split(': ',1)[1] }}",
              "device": "{{ lines[1].split(': ',1)[1] }}",
              "event": {{ lines[2].split(': ',1)[1] }}
            }
            {%- if not loop.last %},{% endif -%}
          {%- endfor -%}
          ]
        {% endif %}

  # 5. Append new entry
  - variables:
      updated: >
        {{ (json_list + [ new_entry | from_json ]) | tojson }}

  # 6. Enforce max history limit
  - variables:
      trimmed: >
        {{
          (updated | from_json)[-max_history_var:]
          | tojson
        }}

  # 7. Convert JSON list → YAML list for final storage
  - variables:
      final_output: "{{ trimmed | from_json | to_yaml }}"

  # 8. Write YAML into the input_text helper
  - action: input_text.set_value
    target:
      entity_id: "{{ log_helper_var }}"
    data:
      value: "{{ final_output }}"
