blueprint:
  homeassistant:
    min_version: 2024.10.0
  domain: automation
  name: [TESTING] IKEA Rodret (E2201) Controls (ZHA/Z2M)
  description: >
    ## Control anything with **IKEA RODRET** remotes


    Only for use with [ZHA](https://www.home-assistant.io/integrations/zha/)
    or Zigbee2MQTT (cf [MQTT](https://www.home-assistant.io/integrations/mqtt)
    + [Z2M addon](https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html)).


    Available controls:

    - Single press **on/off** (Rodret)

    - Double press **on/off** (Rodret, _Optional_)

    - Hold **on/off** (Rodret)
    Actions will be executed every **Hold delay**, but maximum **Max number of loops** times.
#
# Input Block
  input:
    # Device Selector
    remote_device:
      name: Remote
      description: >
        IKEA remote (Somrig, Rodret) to use.
      default: []
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: RODRET Dimmer
            - integration: mqtt
              manufacturer: IKEA
              model: RODRET wireless dimmer/power switch
            # DEPRECATED - for removal, keeping for z2m v1 backward compatibility
            - integration: mqtt
              manufacturer: IKEA
              model: RODRET wireless dimmer/power switch (E2201)
          multiple: false
    #
    #  Define Button Actions
    on_press_action:
      name: Press "on" action
      description: Choose action(s) to run when **on** (Rodret) button is **pressed**.
      default: []
      selector:
        action: {}
    off_press_action:
      name: Press "off" action
      description: Choose action(s) to run when **off** (Rodret) button is **pressed**.
      default: []
      selector:
        action: {}
    on_hold_action:
      name: Hold "on" action
      description: Choose action(s) to run when **on** (Rodret) button is **held**.
      default: []
      selector:
        action: {}
    off_hold_action:
      name: Hold "off" action
      description: Choose action(s) to run when **off** (Rodret) button is **held**.
      default: []
      selector:
        action: {}
    on_double_press_action:
      name: Double press "on" action
      description: >
        Choose action(s) to run when the **on** (Rodret) button is **pressed twice**.

        **_NB for Rodret only_**: **Double press event (on)** must be exposed and **Double press delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    off_double_press_action:
      name: Double press "off" action
      description: >
        Choose action(s) to run when the **off** (Rodret) button is **pressed twice**.

        **_NB for Rodret only_**: **Double press event (off)** must be exposed and **Double press delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    #
    #  Define Button Actions
    helper_section :
      name: Helpers
      icon: mdi:cog-outline
      collapsed: true
      input:
        helper_hold_delay:
          name: Hold delay
          description: Delay between the execution of the **Hold** action(s).
          default: 250
          selector:
            number:
              unit_of_measurement: milliseconds
              min: 100.0
              max: 5000.0
              step: 10.0
              mode: slider
        helper_max_loops:
          name: Max number of loops
          description: Maximum number of loops when holding down a button.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              step: 1.0
              mode: slider
    rodret_options_section:
      name: Rodret options
      icon: mdi:remote
      collapsed: true
      input:
        on_double_press_exposed:
          name: Expose virtual double press "on" event
          description: >
            Choose whether or not to expose the virtual **double press** event for the **on** button.
            Turn this on if you are providing action(s) for the **Double press action (on / 1 dot)**.
          default: false
          selector:
            boolean: {}
        off_double_press_exposed:
          name: Expose virtual double press "off" event
          description: >
            Choose whether or not to expose the virtual **double press** event for the **off** button.
            Turn this on if you are providing an action for the **Double press action (off / 2 dots)**.
          default: false
          selector:
            boolean: {}
        helper_double_press_delay:
          name: Double press delay
          description: >
            Max delay between the first and the second button press for the
            **Double press events**. Provide a value only if you are using a double press action.
            Increase this value if you notice that the double press action is not triggered
            properly.
          default: 250
          selector:
            number:
              unit_of_measurement: milliseconds
              min: 100.0
              max: 5000.0
              step: 10.0
              mode: slider
#
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  # RODRET - E2201
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
      command: "on"
      cluster_id: 6
      endpoint_id: 1
    id: press-on-zha-e2201
  - trigger: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "on"
    id: press-on-z2m-e2201
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
      command: "off"
      cluster_id: 6
      endpoint_id: 1
    id: press-off-zha-e2201
  - trigger: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "off"
    id: press-off-z2m-e2201
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
      command: "move_with_on_off"
      cluster_id: 8
      endpoint_id: 1
      args: [0, 83]
    id: hold-on-zha-e2201
  - trigger: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_move_up"
    id: hold-on-z2m-e2201
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
      command: "move"
      cluster_id: 8
      endpoint_id: 1
      args: [1, 83, 0, 0]
    id: hold-off-zha-e2201
  - trigger: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_move_down"
    id: hold-off-z2m-e2201
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input remote_device
      endpoint_id: 1
      cluster_id: 8
      command: "stop_with_on_off"
    id: release-zha-e2201
  - trigger: device
    domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: "brightness_stop"
    id: release-z2m-e2201
#
# Action Block
actions:
  - variables:
      on_double_press_exposed: !input on_double_press_exposed
      off_double_press_exposed: !input off_double_press_exposed
  - choose:
      #
      # Handle Button Up Single Press / Double Press (Virtual)
      - conditions:
          - condition: trigger
            id:
              - press-on-zha-e2201
              - press-on-z2m-e2201
        sequence:
          - if:
              - condition: template
                value_template: "{{ on_double_press_exposed }}"
            then:
              - choose:
                  - conditions:
                      - condition: trigger
                        id:
                          - press-on-zha-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: event
                            event_type: zha_event
                            event_data:
                              device_id: !input remote_device
                              command: "on"
                              cluster_id: 6
                              endpoint_id: 1
                        timeout:
                          milliseconds: !input helper_double_press_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input on_double_press_action
                        else: !input on_press_action
                  - conditions:
                      - condition: trigger
                        id:
                          - press-on-z2m-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: device
                            domain: mqtt
                            device_id: !input remote_device
                            type: action
                            subtype: "on"
                        timeout:
                          milliseconds: !input helper_double_press_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input on_double_press_action
                        else: !input on_press_action
                default: !input on_press_action
            else: !input on_press_action
      #
      # Handle Button Down Single Press / Double Press (Virtual)
      - conditions:
          - condition: trigger
            id:
              - press-off-zha-e2201
              - press-off-z2m-e2201
        sequence:
          - if:
              - condition: template
                value_template: "{{ off_double_press_exposed }}"
            then:
              - choose:
                  - conditions:
                      - condition: trigger
                        id:
                          - press-off-zha-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: event
                            event_type: zha_event
                            event_data:
                              device_id: !input remote_device
                              command: "off"
                              cluster_id: 6
                              endpoint_id: 1
                        timeout:
                          milliseconds: !input helper_double_press_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input off_double_press_action
                        else: !input off_press_action
                  - conditions:
                      - condition: trigger
                        id:
                          - press-off-z2m-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: device
                            domain: mqtt
                            device_id: !input remote_device
                            type: action
                            subtype: "off"
                        timeout:
                          milliseconds: !input helper_double_press_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input off_double_press_action
                        else: !input off_press_action
                default: !input off_press_action
            else: !input off_press_action
      #
      # Handle Button Up Long Press
      - conditions:
          - condition: trigger
            id:
              - hold-on-zha-e2201
              - hold-on-z2m-e2201
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input on_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-on-zha-e2201
                              sequence:
                                - wait_for_trigger:
                                    - trigger: event
                                      event_type: zha_event
                                      event_data:
                                        device_id: !input remote_device
                                        command: "stop_with_on_off"
                                        cluster_id: 8
                                        endpoint_id: 1
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-on-z2m-e2201
                              sequence:
                                - wait_for_trigger:
                                    - trigger: device
                                      domain: mqtt
                                      device_id: !input remote_device
                                      type: action
                                      subtype: "brightness_stop"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
      #
      # Handle Button Down Long Press
      - conditions:
          - condition: trigger
            id:
              - hold-off-zha-e2201
              - hold-off-z2m-e2201
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input off_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-off-zha-e2201
                              sequence:
                                - wait_for_trigger:
                                    - trigger: event
                                      event_type: zha_event
                                      event_data:
                                        device_id: !input remote_device
                                        command: "stop_with_on_off"
                                        cluster_id: 8
                                        endpoint_id: 1
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-off-z2m-e2201
                              sequence:
                                - wait_for_trigger:
                                    - trigger: device
                                      domain: mqtt
                                      device_id: !input remote_device
                                      type: action
                                      subtype: "brightness_stop"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
