blueprint:
  name: IKEA STYRBAR – Full Button Control (Click/Hold Only - Z2M)
  author: yarafie
  domain: automation
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/styrbar_test.yaml
  description: >
    Full support for STYRBAR remote - Zigbee2MQTT.
    Allows defining Click and Hold actions for all four buttons. Release events are handled internally to stop hold loops.
    Includes a 20-second timeout on hold actions for robustness against missed signals.
  homeassistant:
    min_version: 2024.10.0
#
# Define UI and default values
  input:
    # Device Selector
    button_device:
      name: (Required) IKEA Styrbar Remote Control
      description: Select IKEA STYRBAR Remote Control
      default: []
      selector:
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001-e2002
            - integration: mqtt
              manufacturer: IKEA
              model: STYRBAR remote control
            # For backwards compatability with z2m 1.x. model_id is added to end of model rather than a seperate attribute in z2m 2.x
            - integration: mqtt
              manufacturer: IKEA
              model: STYRBAR remote control (E2001/E2002)
          multiple: false
    # Inputs for custom actions
    action_up_click:
      name: UP Click Action (e.g., Turn Device On)
      default: []
      selector:
        action: {}
    action_up_hold:
      name: UP Hold Action (Loop)
      description: Action to repeat continuously while UP is held (e.g., Increase Brightness/Volume).
      selector:
        action: {}
    action_down_click:
      name: DOWN Click Action (e.g., Turn Device Off)
      default: []
      selector:
        action: {}
    action_down_hold:
      name: DOWN Hold Action (Loop)
      description: Action to repeat continuously while DOWN is held (e.g., Decrease Brightness/Volume).
      selector:
        action: {}
    action_right_click:
      name: RIGHT Click Action
      default: []
      selector:
        action: {}
    action_right_hold:
      name: RIGHT Hold Action (Loop)
      description: Action to repeat continuously while RIGHT is held (e.g., Decrease Brightness/Volume).
      default: []
      selector:
        action: {}
    action_left_click:
      name: LEFT Click Action
      default: []
      selector:
        action: {}
    action_left_hold:
      name: LEFT Hold Action (Loop)
      description: Action to repeat continuously while LEFT is held (e.g., Decrease Brightness/Volume).
      default: []
      selector:
        action: {}
#
# Define mode for automatiom
mode: restart # Ensures only one action sequence runs at a time, critical for hold loops.
#
# Define Triggers for automation
triggers:
  ##############################################
  # Zigbee2MQTT TRIGGERS (Using device action subtypes)
  ##############################################
  # UP Click (Short Press)
  - trigger: device
    id: z2m-up-click
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: 'on'
  # UP Hold (Move Start)
  - trigger: device
    id: z2m-up-hold
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: brightness_move_up
  # DOWN Click (Short Press)
  - trigger: device
    id: z2m-down-click
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: 'off'
  # DOWN Hold (Move Start)
  - trigger: device
    id: z2m-down-hold
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: brightness_move_down
  # UP/DOWN Release (Used internally to stop hold loops)
  # The release action for the Up/Down buttons share one action since there is only one release trigger
  - trigger: device
    id: z2m-up-down-release
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: brightness_stop
  # RIGHT Click
  - trigger: device
    id: z2m-right-click
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_right_click
  # RIGHT Hold
  - trigger: device
    id: z2m-right-hold
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_right_hold
  # RIGHT Release
  - trigger: device
    id: z2m-right-release
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_right_release
  # LEFT Click
  - trigger: device
    id: z2m-left-click
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_left_click
  # LEFT Hold
  - trigger: device
    id: z2m-left-hold
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_left_hold
  # LEFT Release
  - trigger: device
    id: z2m-left-release
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: arrow_left_release
#
# Actions Block
actions: # The main execution sequence.
  - choose:
    #########################################################
    # UP BUTTON CLICK
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-up-click]
      sequence: !input action_up_click
    #########################################################
    # DOWN BUTTON CLICK
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-down-click]
      sequence: !input action_down_click
    #########################################################
    # RIGHT BUTTON CLICK
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-right-click]
      sequence: !input action_right_click
    #########################################################
    # LEFT BUTTON CLICK
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-left-click]
      sequence: !input action_left_click
    #########################################################
    # UP HOLD LOOP (Repeats action until release or timeout)
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-up-hold]
      sequence:
        - repeat:
            # The loop continues WHILE the index is less than 250 (failsafe)
            while:
              - condition: template
                value_template: "{{ repeat.index < 250 }}"
            sequence:
              # 1. Execute the action defined by the blueprint input
              - choose: !input action_left_hold
              # 2. **WAIT FOR RELEASE OR TIMEOUT (80ms)**
              - wait_for_trigger:
                  # z2m triggers
                  - trigger: device
                    domain: mqtt
                    device_id: !input button_device
                    type: action
                    subtype: brightness_stop
                timeout:
                  milliseconds: 80
                continue_on_timeout: true # If 80ms pass, continue running the sequence below
              # 3. **STOP CONDITION (BREAK)**
              # If wait.trigger is NOT None, it means a release event occurred,
              # and this condition being true will cause the loop to stop (break).
              - condition: template
                value_template: "{{ wait.trigger is not none }}"
                alias: "UP Release Event Fired - Stop Loop"
    #########################################################
    # DOWN HOLD LOOP (Repeats action until release or timeout)
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-down-hold]
      sequence:
        - repeat:
            # The loop continues WHILE the index is less than 250 (failsafe)
            while:
              - condition: template
                value_template: "{{ repeat.index < 250 }}"
            sequence:
              # 1. Execute the action defined by the blueprint input
              - choose: !input action_left_hold
              # 2. **WAIT FOR RELEASE OR TIMEOUT (80ms)**
              - wait_for_trigger:
                  # z2m triggers
                  - trigger: device
                    domain: mqtt
                    device_id: !input button_device
                    type: action
                    subtype: brightness_stop
                timeout:
                  milliseconds: 80
                continue_on_timeout: true # If 80ms pass, continue running the sequence below
              # 3. **STOP CONDITION (BREAK)**
              # If wait.trigger is NOT None, it means a release event occurred,
              # and this condition being true will cause the loop to stop (break).
              - condition: template
                value_template: "{{ wait.trigger is not none }}"
                alias: "DOWN Release Event Fired - Stop Loop"
    #########################################################
    # RIGHT HOLD LOOP (Repeats action until release or timeout)
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-right-hold]
      sequence:
        - repeat:
            # The loop continues WHILE the index is less than 250 (failsafe)
            while:
              - condition: template
                value_template: "{{ repeat.index < 250 }}"
            sequence:
              # 1. Execute the action defined by the blueprint input
              - choose: !input action_left_hold
              # 2. **WAIT FOR RELEASE OR TIMEOUT (80ms)**
              - wait_for_trigger:
                  # z2m triggers
                  - trigger: device
                    domain: mqtt
                    device_id: !input button_device
                    type: action
                    subtype: arrow_right_release
                timeout:
                  milliseconds: 80
                continue_on_timeout: true # If 80ms pass, continue running the sequence below
              # 3. **STOP CONDITION (BREAK)**
              # If wait.trigger is NOT None, it means a release event occurred,
              # and this condition being true will cause the loop to stop (break).
              - condition: template
                value_template: "{{ wait.trigger is not none }}"
                alias: "RIGHT Release Event Fired - Stop Loop"
    #########################################################
    # LEFT HOLD LOOP (Repeats action until release or timeout)
    #########################################################
    - conditions:
        - condition: trigger
          id: [z2m-left-hold]
      sequence:
        - repeat:
            # The loop continues WHILE the index is less than 250 (failsafe)
            while:
              - condition: template
                value_template: "{{ repeat.index < 250 }}"
            sequence:
              # 1. Execute the action defined by the blueprint input
              - choose: !input action_left_hold
              # 2. **WAIT FOR RELEASE OR TIMEOUT (80ms)**
              - wait_for_trigger:
                  # z2m triggers
                  - trigger: device
                    domain: mqtt
                    device_id: !input button_device
                    type: action
                    subtype: arrow_left_release
                timeout:
                  milliseconds: 80
                continue_on_timeout: true # If 80ms pass, continue running the sequence below
              # 3. **STOP CONDITION (BREAK)**
              # If wait.trigger is NOT None, it means a release event occurred,
              # and this condition being true will cause the loop to stop (break).
              - condition: template
                value_template: "{{ wait.trigger is not none }}"
                alias: "LEFT Release Event Fired - Stop Loop"
