# ==========================================================
# -------------------------------------------
# IKEA STYRBAR remote control (E2001/E2002)
# -------------------------------------------
#  Button -> action mapping
#  ---------------------------------------------------------
# | Icon                   | Action  | Exposed Action       |
# |---------------------------------------------------------|
# | Light large ( top )    | push    | on                   |
# | Light large ( top )    | hold    | brightness_move_up   |
# | Light large ( top )    | release | brightness_stop      |
# |---------------------------------------------------------|
# | Light small ( bottom ) | push    | off                  |
# | Light small ( bottom ) | hold    | brightness_move_down |
# | Light small ( bottom ) | release | brightness_stop      |
# |---------------------------------------------------------|
# | Arrow left             | push    | arrow_left_click     |
# | Arrow left             | hold    | arrow_left_hold      |
# | Arrow left             | release | arrow_left_release   |
# |---------------------------------------------------------|
# | Arrow right            | push    | arrow_right_click    |
# | Arrow right            | hold    | arrow_right_hold     |
# | Arrow right            | release | arrow_right_release  |
# |---------------------------------------------------------|
# | For the arrow buttons it seems that the hold/move       | 
# | action  takes a bit longer to be send.                  |
#  ---------------------------------------------------------
# Action (enum)
# The possible values are:
#  1. on
#  2. off
#  3. brightness_move_up
#  4. brightness_move_down
#  5. brightness_stop
#  6. arrow_left_click
#  7. arrow_left_hold
#  8. arrow_left_release
#  9. arrow_right_click
# 10. arrow_right_hold
# 11. arrow_right_release
# ==========================================================
blueprint:
  homeassistant:
     min_version: 2024.10.0
  author: yarafie
  domain: automation
  name: z2m - IKEA STYRBAR remote control (E2001/E2002)
  description: "This blueprint is for the IKEA STYRBAR square, 4-button remote when used with zigbee2mqtt.
  It is for general use so all buttons can be connected to any action of your choice"
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/z2m-IKEA-styrbar_E2001_E2002.yaml
#
# Define UI and default values
  input:
    remote_device:
      name: Remote
      description: Select IKEA STYRBAR remote to use
      default: []
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: STYRBAR remote control (E2001/E2002)
          multiple: false
    button_on:
      name: Brightness up button - short press
      description: Action to run when SHORT press on brighness UP button
      default: []
      selector:
        action: {}
    button_off:
      name: Brightness down button - short press
      description: Action to run when SHORT press on brighness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_move_up:
      name: Brightness up button - long press
      description: Action to run when LONG press on brighness UP button
      default: []
      selector:
        action: {}
    button_brightness_move_down:
      name: Brightness down button - long press
      description: Action to run when LONG press on brighness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_stop:
      name: Brightness stop button - long release press
      description: Action to run when LONG press on brighness (up or down) is released
      default: []
      selector:
        action: {}
    button_left_click:
      name: Left button - short press
      description: Action to run when SHORT press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      description: Action to run when HOLD press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_release:
      name: Left button - release
      description: Action to run when RELEASE press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      description: Action to run when SHORT press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      description: Action to run when HOLD press on RIGHT button
      default: []
      selector:
        action: {}
    button_right_release:
      name: Right button - release
      description: Action to run when RELEASE press on RIGHT arrow button
      default: []
      selector:
        action: {}
#
# Define mode for automatiom
mode: restart
max_exceeded: silent
#
# Define Triggers for automation
triggers:
# TOP AND BOTTOM BUTTONS
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: "on"
  id: press-top-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: "off"
  id: press-bottom-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: brightness_move_up
  id: hold-top-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: brightness_move_down
  id: hold-bottom-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: brightness_stop
  id: release-z2m-e2001
# ARROW LEFT BUTTON
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_left_click
  id: press-left-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_left_hold
  id: hold-left-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_left_release
  id: release-left-z2m-e2001
# ARROW RIGHT BUTTON
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_right_click
  id: press-right-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_right_hold
  id: hold-right-z2m-e2001
- trigger: device
  domain: mqtt
  device_id: !input remote_device
  type: action
  subtype: arrow_right_release
  id: release-right-z2m-e2001
#
# Define actions
actions:
- choose:
# TOP AND BOTTOM BUTTONS
  - conditions:
    - condition: trigger
      id:
      - press-top-z2m-e2001
    sequence: !input "button_on"
  - conditions:
    - condition: trigger
      id:
      - press-bottom-z2m-e2001
    sequence: !input "button_off"
  - conditions:
    - condition: trigger
      id:
      - hold-top-z2m-e2001
    sequence: !input "button_brightness_move_up"
  - conditions:
    - condition: trigger
      id:
      - hold-bottom-z2m-e2001
    sequence: !input "button_brightness_move_down"
  - conditions:
    - condition: trigger
      id:
      - release-z2m-e2001
    sequence: !input "button_brightness_stop"
#ARROW LEFT
  - conditions:
    - condition: trigger
      id:
      - press-left-z2m-e2001
    sequence: !input "button_left_click"
  - conditions:
    - condition: trigger
      id:
      - hold-left-z2m-e2001
    sequence: !input "button_left_hold"
  - conditions:
    - condition: trigger
      id:
      - release-left-z2m-e2001
    sequence: !input "button_left_release"
#ARROW RIGHT
  - conditions:
    - condition: trigger
      id:
      - press-right-z2m-e2001
    sequence: !input "button_right_click"
  - conditions:
    - condition: trigger
      id:
      - hold-right-z2m-e2001
    sequence: !input "button_right_hold"
  - conditions:
    - condition: trigger
      id:
      - release-right-z2m-e2001
    sequence: !input "button_right_release"
