# Blueprint Metadata
blueprint:
  name: Blueprint Testing
  description: |
    # Blueprint Testing

    Blueprint Testing

  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/Testing/Blueprint_Testing.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  # Device Selector
  input:
    controller_device:
      name: Device
      description: The device to use for the Blueprint Testing.
      default: ''
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
          multiple: false
    ## inputs switch mode selection
    module_mode_option:
      name: (Optional) The mode the module operates
      description: The mode the module to set to
      default: single_rocker
      selector:
        select:
            options:
              - label: Single Rocker
                value: single_rocker
              - label: Single Push Button
                value: single_push_button
              - label: Dual Rocker
                value: dual_rocker
              - label: Dual Push Button
                value: dual_push_button
            mode: dropdown
#
# Automation schema
variables:
  # Controller ID
  controller_id: !input controller_device
  module_mode_option: !input module_mode_option
  #friendly_name: {{ state_attr(controller_id, 'friendly_name') }}
#
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  - platform: event
    event_type: blueprint_testing_event
    event_data:
      controller_id: !input controller_device
# Conditions Block
conditions: []
#
# Actions Block
actions:
  # Define Action Variables
  - variables:
      friendly_name: {{ state_attr(controller_id, 'friendly_name') }}
      #topic_var: zigbee2mqtt/{{ state_attr(controller_id, 'friendly_name') }}/set
      #payload_var: "{"device_mode":" {{ module_mode_option }} }"
  # Actions
  - action: notify.mobile_app_yasirs_fold4
    metadata: {}
    data:
      title: "Blueprint Testing"
      message: >-
           controller_id: {{ controller_id }} \n
           module_option: {{ module_mode_option }} \n
           friendly_name: {{ friendly_name }} \n
#           topic_var    : {{ topic_var }} \n
#           payload_var  : {{ payload_var }} \n
#           topic        : zigbee2mqtt/{{ state_attr(controller_id, 'friendly_name') }}/set
#           payload      : "{"device_mode":" {{ module_mode_option }} }"
      data:
        alert_once: true
        ttl: 0
        priority: high
        group: Blueprint Testing
        channel: alarm_stream
        color: "#03a9f4"
        notification_icon: mdi:cctv
        sticky: true
        push:
          interruption-level: passive
          sound:
            name: default
            volume: 1
