..
..
input:
    zigbee_device:
      name: Zigbee Devices - Tuya TS0044 4 Buttons (and alike)
      description: Select the correct Zigbee devices to use.
      selector:
        device:
          integration: mqtt
          multiple: false
..
..
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action
variables:
  device_names: !input zigbee_device
  expected_topics: >
    {% for device_name in device_names %}
      zigbee2mqtt/{{ device_attr(device_name, 'name') }}/action |
    {% endfor %}null
condition:
  - condition: template
    value_template: "{{ trigger.topic in expected_topics }}"
action:
  - variables:
      command: "{{ trigger.payload }}"
  - choose:
      - conditions:
          - "{{ command == '1_single' }}"
        sequence: !input button_one_short_press
..
..

The thing is with code snippet using MQTT messages is that the automation triggers on ANY ‘action’ message and only afterwards filters it via a condition.
